#!/bin/bash

# WARNING: Please, DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# Git hook to check prose style
#
# Usage:
#   $ check={all,staged-changes,working-tree-changes,branch} ./check-english-usage.sh
#
# Exit codes:
#   0 - All files are formatted correctly
#   1 - Files are not formatted correctly
#
# The `check` parameter controls which files are checked, so you can
# limit the scope of the check according to what is appropriate at the
# point the check is being applied.
#
#   check=all: check all files in the repository
#   check=staged-changes: check only files staged for commit.
#   check=working-tree-changes: check modified, unstaged files. This is the default.
#   check=branch: check for all changes since branching from $BRANCH_NAME

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"
  apply-key-value-args "$@"

  check=${check:-working-tree-changes}
  case $check in
    "all")
      filter="git ls-files -z"
      ;;
    "staged-changes")
      filter="git diff --diff-filter=ACMRT --name-only --cached -z"
      ;;
    "working-tree-changes")
      filter="git diff --diff-filter=ACMRT --name-only -z"
      ;;
    "branch")
      filter="git diff --diff-filter=ACMRT --name-only -z ${BRANCH_NAME:-origin/main}"
      ;;
    *)
      echo "Unrecognised check mode: $check" >&2 && exit 1
      ;;
  esac

  if command -v vale > /dev/null 2>&1 && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    filter="$filter" run-vale-natively
  else
    filter="$filter" run-vale-in-docker
  fi
}

# Run Vale natively.
# Arguments (provided as environment variables):
#   filter=[git command to filter the files to check]
function run-vale-natively() {

  local files=()
  while IFS= read -r -d '' file; do
    files+=("$file")
  done < <($filter)

  # If no files found, exit successfully
  [[ ${#files[@]} -eq 0 ]] && return 0

  vale \
    --config "$PWD/scripts/config/vale/vale.ini" \
    "${files[@]}"
}

# Run Vale in a Docker container.
# Arguments (provided as environment variables):
#   filter=[git command to filter the files to check]
function run-vale-in-docker() {

  # shellcheck disable=SC1091
  source ./scripts/docker/docker.lib.sh

  # shellcheck disable=SC2155
  local image=$(name=jdkato/vale docker-get-image-version-and-pull)

  local files=()
  while IFS= read -r -d '' file; do
    files+=("$file")
  done < <($filter)

  # We use /dev/null here to stop `vale` from complaining that it's
  # not been called correctly if the $filter happens to return an
  # empty list. As long as there's a filename, even if it's one that
  # will be ignored, `vale` is happy.
  if [[ ${#files[@]} -eq 0 ]]; then
    files=(/dev/null)
  fi

  docker run --rm --platform linux/amd64 \
    --volume "$PWD:/workdir" \
    --workdir /workdir \
    "$image" \
      --config /workdir/scripts/config/vale/vale.ini \
      "${files[@]}"
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# Parse arguments passed by pre-commit as KEY=VALUE and expose them as env vars.
function apply-key-value-args() {

  for arg in "$@"; do
    if [[ "$arg" =~ ^[A-Za-z_][A-Za-z0-9_]*=.+$ ]]; then
      export "$arg"
    else
      echo "Unknown argument format: $arg (expected key=value)" >&2
      exit 126
    fi
  done
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
