# Pre-commit Hook Manifest
# This file defines hooks that this repository PROVIDES to other repos.
# Service repos reference these via: repo: https://github.com/NHSDigital/nhs-notify-shared-modules
#
# This is NOT the pre-commit config for this repo (that's in scripts/config/pre-commit.yaml)

- id: sort-dictionary
  name: Sort dictionary
  entry: scripts/githooks/sort-dictionary.sh
  language: script
  pass_filenames: false

- id: scan-secrets
  name: Scan secrets
  entry: scripts/githooks/scan-secrets.sh
  language: script
  pass_filenames: false

- id: check-file-format
  name: Check file format
  entry: scripts/githooks/check-file-format.sh
  language: script
  pass_filenames: false
