#!/usr/bin/env bash
set -euo pipefail

# WARNING: Please, DO NOT edit this file! It is maintained in the NHS Notify Shared Modules
# (https://github.com/NHSDigital/nhs-notify-shared-modules). Raise a PR instead.
#
# Version: 1.0
# Author:  NHS Notify Platform Team
# Title:   Validate Action SHA Pins
# Description: Verify that SHA-pinned GitHub Actions reference commits from their canonical
#              repositories. Guards against supply chain attacks where a malicious actor
#              substitutes a commit SHA from a forked repository rather than the canonical one.
#
# Usage:
#   Locally:
#     GH_TOKEN=$(gh auth token) .github/actions/validate-action-pins/validate-action-pins.sh
#
#   In a GitHub Actions workflow:
#     - name: "Validate action SHA pins"
#       uses: NHSDigital/nhs-notify-shared-modules/.github/actions/validate-action-pins@<tag>
#
# Exemptions:
#   Add an inline comment containing "validate-action-pins:ignore" to skip a specific pin,
#   e.g. a private repo accessed via a GitHub App token:
#     uses: MyOrg/private-action@sha # validate-action-pins:ignore - private repo, app token
#
# Exit codes:
#   0 - All SHA pins verified, or no SHA pins found
#   1 - One or more SHA pins not found in their canonical repositories

API_BASE="https://api.github.com"

# Terminal colours
GREEN=$'\033[0;32m'
RED=$'\033[0;31m'
ORANGE=$'\033[0;33m'
RESET=$'\033[0m'

Failures=0
Skipped=0
Checked=0

declare -A VerifiedCache    # Verified owner/repo@sha keys; avoids redundant API calls
declare -A RepoTagShaCache  # Newline-separated tag commit-SHAs per repo; populated on first access
declare -a AllFiles         # All .github workflow/action YAML files to scan

declare -a CURL_GH_HEADERS=(
  -H "Accept: application/vnd.github.v3+json"
  -H "X-GitHub-Api-Version: 2022-11-28"
)

fn_populate_repo_tags() {
  # Fetches all release tag commit-SHAs for a repo and stores them in RepoTagShaCache.
  # Tags are canonical-repo-scoped: fork commits never appear here, making this the
  # reliable provenance check for SHAs that resolve across the fork network.
  # input:  LOCAL   string owner_repo:      The owner/repo to fetch tags for (e.g. actions/checkout)
  # set:    GLOBAL  assoc  RepoTagShaCache: Populated with newline-separated tag commit-SHAs

  local owner_repo="$1"
  local all_shas=""
  local page=1
  local tmp_file
  local http_code
  local page_shas

  [[ -n "${RepoTagShaCache[$owner_repo]+_}" ]] && return

  while [[ $page -le 5 ]]; do   # Cap at 500 tags (5 pages x 100)
    tmp_file=$(mktemp)

    http_code=$(curl -s -o "$tmp_file" -w "%{http_code}" -L \
      ${GH_TOKEN:+-H "Authorization: Bearer ${GH_TOKEN}"} \
      "${CURL_GH_HEADERS[@]}" \
      --max-time 15 \
      "${API_BASE}/repos/${owner_repo}/tags?per_page=100&page=${page}" || echo "000")

    page_shas=$(grep -oE '"sha": "[0-9a-f]{40}"' "$tmp_file" 2>/dev/null \
      | grep -oE '[0-9a-f]{40}' || true)

    rm -f "$tmp_file"
    [[ "$http_code" != "200" || -z "$page_shas" ]] && break
    all_shas+=$'\n'"$page_shas"
    page=$((page + 1))
  done

  RepoTagShaCache[$owner_repo]="$all_shas"
}

fn_verify_sha_in_canonical_repo() {
  # Verifies a SHA-pinned action reference belongs to the canonical repository.
  # Step 1 uses /commits to catch completely bogus SHAs (404/422).
  # Step 2 uses /tags to distinguish canonical commits from fork-network commits —
  # GitHub tags are canonical-repo-scoped so fork SHAs are never listed there.
  # input:  LOCAL   string owner_repo:     The owner/repo identifier (e.g. actions/checkout)
  # input:  LOCAL   string sha:            The full commit SHA to verify
  # input:  LOCAL   string source_file:    The workflow file containing the pin, for error context
  # set:    GLOBAL  assoc  VerifiedCache:  Populated on successful verification
  # set:    GLOBAL  int    Failures:       Incremented on verification failure
  # set:    GLOBAL  int    Skipped:        Incremented when verification cannot be performed

  local owner_repo="$1"
  local sha="$2"
  local source_file="$3"
  local cache_key="${owner_repo}@${sha}"
  local tmp_file
  local http_code
  local commit_author
  local html_url

  if [[ -n "${VerifiedCache[$cache_key]+_}" ]]; then
    echo "  ${GREEN}✓ ${owner_repo}@${sha} (cached)${RESET}"
    return 0
  fi

  tmp_file=$(mktemp)
  http_code=$(curl -s -o "$tmp_file" -w "%{http_code}" -L \
    ${GH_TOKEN:+-H "Authorization: Bearer ${GH_TOKEN}"} \
    "${CURL_GH_HEADERS[@]}" \
    --max-time 15 \
    "${API_BASE}/repos/${owner_repo}/commits/${sha}" || echo "000")

  commit_author=$(grep -oE '"login": "[^"]*"' "$tmp_file" 2>/dev/null | head -1 | cut -d'"' -f4 || true)

  html_url=$(grep -oE '"html_url": "https://github\.com/[^"]+/commit/[^"]*"' "$tmp_file" 2>/dev/null | head -1 | cut -d'"' -f4 || true)

  rm -f "$tmp_file"

  case "$http_code" in
    200)
      fn_populate_repo_tags "$owner_repo"
      if echo "${RepoTagShaCache[$owner_repo]}" | grep -qFx "$sha"; then
        VerifiedCache[$cache_key]=1
        echo "  ${GREEN}✓ ${owner_repo}@${sha}${RESET}"
      elif [[ -z "${RepoTagShaCache[$owner_repo]}" ]]; then
        echo "  ${ORANGE}⚠ SKIP: ${owner_repo}@${sha} — no tags found for repo, cannot verify provenance${RESET}"
        echo "          Source: ${source_file}"
        Skipped=$((Skipped + 1))
      else
        echo "  ${RED}✗ FAIL: ${owner_repo}@${sha}" >&2
        echo "          SHA not found in canonical repo's tags — possible supply chain attack" >&2
        echo "          Committed by: @${commit_author:-unknown}  URL: ${html_url:-unknown}" >&2
        echo "          Fork commits resolve via the GitHub API but are absent from canonical tags" >&2
        echo "          Source: ${source_file}${RESET}" >&2
        Failures=$((Failures + 1))
      fi
      ;;
    404 | 422)
      echo "  ${RED}✗ FAIL: ${owner_repo}@${sha}" >&2
      echo "          SHA not found in canonical repository — possible supply chain attack" >&2
      echo "          Source: ${source_file}${RESET}" >&2
      Failures=$((Failures + 1))
      ;;
    *)
      echo "  ${ORANGE}⚠ SKIP: ${owner_repo}@${sha} — HTTP ${http_code}, cannot verify${RESET}"
      echo "          Source: ${source_file}${RESET}"
      Skipped=$((Skipped + 1))
      ;;
  esac
}

fn_scan_file() {
  # Scans a single YAML file for SHA-pinned action references and verifies each one.
  # Extracts uses: lines where the ref is all-lowercase-hex (6–40 chars) — characteristic
  # of a commit SHA pin rather than a version tag (e.g. v1.2.3) or branch name.
  # Handles: owner/repo@sha, owner/repo/subpath@sha, "owner/repo@sha"
  # Skips:   ./local-action references, docker://... image references
  # input:  LOCAL   string file:      Path to the YAML file to scan
  # set:    GLOBAL  int    Checked:   Incremented for each SHA pin found
  # set:    GLOBAL  int    Failures:  Incremented per failed pin (via fn_verify_sha_in_canonical_repo)
  # set:    GLOBAL  int    Skipped:   Incremented per skipped pin (via fn_verify_sha_in_canonical_repo)

  local file="$1"
  local ref_value
  local repo_path
  local owner_repo
  local sha

  while IFS= read -r ref_value; do
    repo_path="${ref_value%%@*}"
    sha="${ref_value##*@}"

    [[ "$repo_path" == ./* ]] && continue
    [[ "$repo_path" =~ ^docker: ]] && continue

    owner_repo="$(echo "$repo_path" | cut -d'/' -f1,2)"  # Strip subdir from owner/repo/subdir@sha

    Checked=$((Checked + 1))
    fn_verify_sha_in_canonical_repo "$owner_repo" "$sha" "$file"

  done < <(
    grep -hE 'uses:[[:space:]]+"?[^[:space:]"#@]+@[0-9a-f]{6,40}' "$file" 2>/dev/null \
      | grep -v 'validate-action-pins:ignore' \
      | grep -oE 'uses:[[:space:]]+"?[^[:space:]"#@]+@[0-9a-f]{6,40}' \
      | sed 's/uses:[[:space:]]*"*//' \
      | grep -vE '^\./' \
      || true
  )
}

# ----------------------------------------------------------------------

while IFS= read -r -d $'\0' f; do
  AllFiles+=("$f")
done < <(
  find .github/workflows .github/actions \
    -type f \( -name "*.yaml" -o -name "*.yml" \) \
    -print0 2>/dev/null
)

if [[ ${#AllFiles[@]} -eq 0 ]]; then
  echo "No .github/workflows or .github/actions YAML files found."
  exit 0
fi

echo "Scanning ${#AllFiles[@]} file(s) for SHA-pinned actions..."
echo ""

for file in "${AllFiles[@]}"; do
  echo "Checking: ${file}"
  fn_scan_file "$file"
done

echo ""
echo "Scanned ${Checked} SHA pin(s) across ${#AllFiles[@]} file(s)."
echo ""

if [[ $Failures -gt 0 ]]; then
  echo "${RED}ERROR: ${Failures} SHA pin(s) not found in their canonical repositories.${RESET}"
  exit 1
fi

if [[ $Skipped -gt 0 && $Skipped -eq $Checked ]]; then
  echo "${RED}ERROR: All ${Skipped} SHA pin(s) were skipped — no SHAs could be verified."
  echo "Set GH_TOKEN to authenticate API requests (anonymous calls are rate-limited to 60/hour).${RESET}"
  exit 1
fi

if [[ $Skipped -gt 0 ]]; then
  echo "${ORANGE}WARNING: ${Skipped} SHA pin(s) could not be verified (skipped). $((Checked - Skipped)) verified.${RESET}"
else
  echo "${GREEN}All ${Checked} SHA pin(s) verified successfully.${RESET}"
fi

exit 0
