#!/bin/bash

# WARNING: Please DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# A set of Terraform functions written in Bash.
#
# Usage:
#   $ source ./terraform.lib.sh

# ==============================================================================
# Common Terraform functions.

# Format Terraform code.
# Arguments (provided as environment variables):
#   dir=[path to a directory where the command will be executed, relative to the project's top-level directory, default is '.']
#   opts=[options to pass to the Terraform fmt command, default is '-recursive']
function terraform-fmt() {
  for d in "${PWD}infrastructure/"*; do
    if [ -d "$d" ]; then
        terraform fmt --recursive "${d}"
    fi
  done
}
