name: "TFSec Scan"
description: "Scan HCL using TFSec"
runs:
  using: "composite"
  steps:
    - name: "TFSec Scan - Components"
      shell: bash
      run: |
        modules_exit_code=0

        ./scripts/terraform/tfsec.sh ./infrastructure/modules || modules_exit_code=$?

        if [ $modules_exit_code -ne 0 ]; then
          echo "One or more TFSec scans failed."
          exit 1
        fi
