#!/bin/bash

# WARNING: Please, DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# Pre-commit git hook to scan for secrets hard-coded in the codebase. This is a
# gitleaks command wrapper. It will run gitleaks natively if it is installed,
# otherwise it will run it in a Docker container.
#
# Usage:
#   $ [options] ./scan-secrets.sh
#
# Options:
#   check={whole-history,last-commit,staged-changes}  # Type of the check to run, default is 'staged-changes'
#   FORCE_USE_DOCKER=true                             # If set to true the command is run in a Docker container, default is 'false'
#   VERBOSE=true                                      # Show all the executed commands, default is 'false'
#
# Exit codes:
#   0 - No leaks present
#   1 - Leaks or error encountered
#   126 - Unknown flag

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"
  apply-key-value-args "$@"

  if command -v gitleaks > /dev/null 2>&1 && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    dir="$PWD"
    cmd="$(get-cmd-to-run)" run-gitleaks-natively
  else
    dir="/workdir"
    cmd="$(get-cmd-to-run)" run-gitleaks-in-docker
  fi
}

# Get Gitleaks command to execute and configuration.
# Arguments (provided as environment variables):
#   dir=[project's top-level directory]
function get-cmd-to-run() {

  check=${check:-staged-changes}
  case $check in
    "whole-history")
      cmd="detect --source $dir --verbose --redact"
      ;;
    "last-commit")
      cmd="detect --source $dir --verbose --redact --log-opts -1"
      ;;
    "staged-changes")
      cmd="protect --source $dir --verbose --staged"
      ;;
  esac
  # Include base line file if it exists
  if [ -f "$dir/scripts/config/.gitleaks-baseline.json" ]; then
    cmd="$cmd --baseline-path $dir/scripts/config/.gitleaks-baseline.json"
  fi
  # Include the config file
  cmd="$cmd --config $dir/scripts/config/gitleaks.toml"

  echo "$cmd"
}

# Run Gitleaks natively.
# Arguments (provided as environment variables):
#   cmd=[command to run]
function run-gitleaks-natively() {

  local output_file
  output_file="$(mktemp)"

  # Prefer pseudo-terminal capture to preserve gitleaks' own colour output.
  if command -v script > /dev/null 2>&1 && [ -t 1 ] && [ -z "${CI:-}" ]; then
    # shellcheck disable=SC2086
    if ! script -q "$output_file" gitleaks $cmd; then
      if output-has-findings "$output_file"; then
        show-secret-scan-help
      fi
      rm -f "$output_file"
      return 1
    fi
  else
    # shellcheck disable=SC2086
    if ! gitleaks $cmd > "$output_file" 2>&1; then
      cat "$output_file"
      if output-has-findings "$output_file"; then
        show-secret-scan-help
      fi
      rm -f "$output_file"
      return 1
    fi

    cat "$output_file"
  fi

  rm -f "$output_file"
}

# Run Gitleaks in a Docker container.
# Arguments (provided as environment variables):
#   cmd=[command to run]
#   dir=[directory to mount as a volume]
function run-gitleaks-in-docker() {

  # shellcheck disable=SC1091
  source ./scripts/docker/docker.lib.sh

  # shellcheck disable=SC2155
  local image=$(name=ghcr.io/gitleaks/gitleaks docker-get-image-version-and-pull)
  local output_file
  output_file="$(mktemp)"
  local docker_tty_args=()
  if [ -t 1 ]; then
    docker_tty_args+=(--tty)
  fi

  # Prefer pseudo-terminal capture to preserve gitleaks' own colour output.
  if command -v script > /dev/null 2>&1 && [ -t 1 ] && [ -z "${CI:-}" ]; then
    # shellcheck disable=SC2086
    if ! script -q "$output_file" docker run --rm --platform linux/amd64 \
      "${docker_tty_args[@]}" \
      --volume "$PWD:$dir" \
      --workdir $dir \
      "$image" \
        $cmd; then
      if output-has-findings "$output_file"; then
        show-secret-scan-help
      fi
      rm -f "$output_file"
      return 1
    fi
  else
    # shellcheck disable=SC2086
    if ! docker run --rm --platform linux/amd64 \
      "${docker_tty_args[@]}" \
      --volume "$PWD:$dir" \
      --workdir $dir \
      "$image" \
        $cmd > "$output_file" 2>&1; then
      cat "$output_file"
      if output-has-findings "$output_file"; then
        show-secret-scan-help
      fi
      rm -f "$output_file"
      return 1
    fi

    cat "$output_file"
  fi

  rm -f "$output_file"
}

# Return success when gitleaks output appears to contain findings.
function output-has-findings() {

  [ -s "$1" ] && grep -Eq '(^|[[:space:]])(RuleID|Finding|FingerPrint):|"RuleID"' "$1"
}

# Print clear remediation guidance when gitleaks reports findings.
function show-secret-scan-help() {

  local reset=""
  local bold=""
  local red=""
  local yellow=""
  local cyan=""

  # Use colours in interactive terminals unless explicitly disabled.
  if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
    reset="\033[0m"
    bold="\033[1m"
    red="\033[31m"
    yellow="\033[33m"
    cyan="\033[36m"
  fi

  printf "\n${bold}${red}[!!!] Secret scan failed.${reset}\n\n"
  printf '%b\n' "${bold}${yellow}If this is a real secret:${reset}"
  printf '%s\n\n' '- Remove and rotate the secret immediately.'
  printf '%b\n' "${bold}${yellow}If this is a false positive:${reset}"
  printf '%s\n' '- Follow PLAT-KOP-020 for handling and safely ignoring gitleaks false positives:'
  printf '%b\n\n' "  ${cyan}https://nhsd-confluence.digital.nhs.uk/spaces/RIS/pages/1429674058/PLAT-KOP-020+-+Handling+and+Safely+Ignoring+Gitleaks+False+Positives${reset}"
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# Parse arguments passed by pre-commit as KEY=VALUE and expose them as env vars.
function apply-key-value-args() {

  for arg in "$@"; do
    if [[ "$arg" =~ ^[A-Za-z_][A-Za-z0-9_]*=.+$ ]]; then
      export "$arg"
    else
      echo "Unknown argument format: $arg (expected key=value)" >&2
      exit 126
    fi
  done
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
