name: "Check Markdown format"
description: "Check Markdown format"
runs:
  using: "composite"
  steps:
    - name: "Check Markdown format"
      shell: bash
      run: |
        export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
        check=branch ${{ github.action_path }}/check-markdown-format.sh
