#!/bin/bash

# WARNING: Please, DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_TOOLING_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TOOLING_ROOT="${TOOLING_ROOT:-${DEFAULT_TOOLING_ROOT}}"

# Script to scan an SBOM file for CVEs (Common Vulnerabilities and Exposures).
# This is a grype command wrapper. It will run grype natively if it is
# installed, otherwise it will run it in a Docker container.
#
# Usage:
#   $ [options] ./scan-vulnerabilities.sh
#
# Options:
#   BUILD_DATETIME=%Y-%m-%dT%H:%M:%S%z  # Build datetime, default is `date -u +'%Y-%m-%dT%H:%M:%S%z'`
#   FORCE_USE_DOCKER=true               # If set to true the command is run in a Docker container, default is 'false'
#   VERBOSE=true                        # Show all the executed commands, default is `false`
#
# Depends on:
#   $ ./create-sbom-report.sh

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"
  trap cleanup-generated-grype-config EXIT

  create-report
  enrich-report
}

function create-report() {

  prepare-grype-config

  if command -v grype > /dev/null 2>&1 && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    run-grype-natively
  else
    run-grype-in-docker
  fi
}

function run-grype-natively() {

  local fail_on_severity=${GRYPE_FAIL_ON_SEVERITY:-}
  local fail_on_opt=""
  if [[ -n "$fail_on_severity" && "$fail_on_severity" != "none" ]]; then
    fail_on_opt="--fail-on $fail_on_severity"
  fi

  # shellcheck disable=SC2086
  grype \
    sbom:"$PWD/sbom-repository-report.json" \
    --config "$GRYPE_CONFIG_FILE" \
    --output json \
    $fail_on_opt \
    --file "$PWD/vulnerabilities-repository-report.tmp.json"
}

function run-grype-in-docker() {

  # shellcheck disable=SC1091
  source "$TOOLING_ROOT/scripts/docker/docker.lib.sh"

  # shellcheck disable=SC2155
  local image=$(name=ghcr.io/anchore/grype docker-get-image-version-and-pull)

  local fail_on_severity=${GRYPE_FAIL_ON_SEVERITY:-}
  local fail_on_opt=""
  if [[ -n "$fail_on_severity" && "$fail_on_severity" != "none" ]]; then
    fail_on_opt="--fail-on $fail_on_severity"
  fi

  # shellcheck disable=SC2086
  docker run --rm --platform linux/amd64 \
    --volume "$PWD":/workdir \
    --volume "$TOOLING_ROOT":/tooling \
    --volume /tmp/grype/db:/.cache/grype/db \
    "$image" \
      sbom:/workdir/sbom-repository-report.json \
      --config "/tooling${GRYPE_CONFIG_FILE#${TOOLING_ROOT}}" \
      --output json \
      $fail_on_opt \
      --file /workdir/vulnerabilities-repository-report.tmp.json
}

function enrich-report() {

  if [[ ! -f vulnerabilities-repository-report.tmp.json ]]; then
    echo "Grype did not produce vulnerabilities-repository-report.tmp.json" >&2
    return 1
  fi

  build_datetime=${BUILD_DATETIME:-$(date -u +'%Y-%m-%dT%H:%M:%S%z')}
  git_url=$(git config --get remote.origin.url)
  git_branch=$(git rev-parse --abbrev-ref HEAD)
  git_commit_hash=$(git rev-parse HEAD)
  git_tags=$(echo \""$(git tag | tr '\n' ',' | sed 's/,$//' | sed 's/,/","/g')"\" | sed 's/""//g')
  pipeline_run_id=${GITHUB_RUN_ID:-0}
  pipeline_run_number=${GITHUB_RUN_NUMBER:-0}
  pipeline_run_attempt=${GITHUB_RUN_ATTEMPT:-0}

  # shellcheck disable=SC2086
  jq \
    '.creationInfo |= . + {"created":"'${build_datetime}'","repository":{"url":"'${git_url}'","branch":"'${git_branch}'","tags":['${git_tags}'],"commitHash":"'${git_commit_hash}'"},"pipeline":{"id":'${pipeline_run_id}',"number":'${pipeline_run_number}',"attempt":'${pipeline_run_attempt}'}}' \
    vulnerabilities-repository-report.tmp.json \
      > vulnerabilities-repository-report.json
  rm -f vulnerabilities-repository-report.tmp.json
}

function prepare-grype-config() {

  GRYPE_CONFIG_FILE="$TOOLING_ROOT/scripts/config/grype.yaml"
  GENERATED_GRYPE_CONFIG_FILE=""

  local ignore_file="$PWD/.grypeignore"
  if [[ ! -f "$ignore_file" ]]; then
    return 0
  fi

  local has_ignores=false
  while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
    local vulnerability_id
    vulnerability_id=$(echo "$raw_line" | sed 's/#.*//' | xargs)
    [[ -z "$vulnerability_id" ]] && continue

    if [[ "$has_ignores" == false ]]; then
      GENERATED_GRYPE_CONFIG_FILE=$(mktemp)
      cat "$GRYPE_CONFIG_FILE" > "$GENERATED_GRYPE_CONFIG_FILE"
      printf '\nignore:\n' >> "$GENERATED_GRYPE_CONFIG_FILE"
      has_ignores=true
    fi

    printf '  - vulnerability: %s\n' "$vulnerability_id" >> "$GENERATED_GRYPE_CONFIG_FILE"
  done < "$ignore_file"

  if [[ "$has_ignores" == false ]]; then
    return 0
  fi

  GRYPE_CONFIG_FILE="$GENERATED_GRYPE_CONFIG_FILE"
}

function cleanup-generated-grype-config() {

  if [[ -n "${GENERATED_GRYPE_CONFIG_FILE:-}" && -f "$GENERATED_GRYPE_CONFIG_FILE" ]]; then
    rm -f "$GENERATED_GRYPE_CONFIG_FILE"
  fi
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
