name: "Trivy Scan"
runs:
  using: "composite"
  steps:
    - name: "Trivy Terraform IAC Scan"
      shell: bash
      run: |
        modules_exit_code=0

        ./scripts/terraform/trivy.sh ./infrastructure/modules || modules_exit_code=$?

        if [ $components_exit_code -ne 0 ] || [ $modules_exit_code -ne 0 ]; then
          echo "Trivy misconfigurations detected."
          exit 1
        fi
