name: "Trivy Scan"
runs:
  using: "composite"
  steps:
    - name: "Trivy Terraform IAC Scan"
      shell: bash
      run: |
        components_exit_code=0
        modules_exit_code=0

        if [ -d ./infrastructure/terraform/components ]; then
          ./scripts/terraform/trivy.sh ./infrastructure/terraform/components || components_exit_code=$?
        fi

        if [ -d ./infrastructure/terraform/modules ]; then
          ./scripts/terraform/trivy.sh ./infrastructure/terraform/modules || modules_exit_code=$?
        fi

        if [ $components_exit_code -ne 0 ] || [ $modules_exit_code -ne 0 ]; then
          echo "Trivy misconfigurations detected."
          exit 1
        fi
